--- #YAML:1.0
name: CGI-Application-Plugin-FillInForm
version: 1.01
author:
  - Mark Stosberg <mark@summersault.com>
abstract: integrate with HTML::FillInForm
license: perl
requires:
  HTML::FillInForm: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::FillInForm:
    file: lib/CGI/Application/Plugin/FillInForm.pm
    version: 1.01
generated_by: Module::Build version 0.2611
